export default {
  base: 'dark',
  dark: true,
  fontFamily:
    '-apple-system, BlinkMacSystemFont, Avenir Next, Avenir, Helvetica, sans-serif',
  background: '#14191e',
  backgroundHover: '#33383d',
  backgroundActive: '#3a4248',
  foreground: '#eee',
  lightTextColor: '#ccc',
  lighterTextColor: '#888',
  inputBorder: 'rgb(140, 140, 140)',
  selectionBackground: '#c0c0c0',
  selectionColor: '#eee',
  summaryColor: '#aaa',
  linkColor: '#6fd7d7',
  inputColor: '#5ac',
  numberColor: '#9ce',
  valueColor: '#dd9',
  bubble1: '#6f6f6f',
  bubble2: '#0d3a4c',
  menuBackground: '#777',
  menuHighlight: '#878787',
  errorColor: '#c00',
  actionColor: '#999',
  primaryActionColor: '#aee',
  actionTextColor: '#111',
  disabledActionColor: '#575757',
  disabledActionTextColor: '#999',
  codeTheme: 'material-ocean',
}
