export default {
  foreground: '#111',
  lightTextColor: '#444',
  background: '#e7e7e7',
  backgroundHover: '#d7d7d7',
  inputBorder: 'rgb(140, 140, 140)',
  selectionBackground: '#7ec0ee',
  selectionColor: 'black',
  linkColor: '#2562b1',
  summaryColor: '#444',
  inputColor: '#297',
  numberColor: '#407',
  valueColor: '#550',
  bubble1: '#c8c8c8',
  menuBackground: '#bbb',
  menuHighlight: '#aaa',
  errorColor: '#f00',
  actionColor: '#444',
  primaryActionColor: '#5a5',
  actionTextColor: '#ccc',
  disabledActionColor: '#bbb',
  disabledActionTextColor: '#888',
}
