export default {
  base: 'light',
  light: true,
  fontFamily:
    '-apple-system, BlinkMacSystemFont, Avenir Next, Avenir, Helvetica, sans-serif',
  foreground: '#111',
  lightTextColor: '#444',
  lighterTextColor: '#888',
  background: '#f7f7f7',
  backgroundHover: '#d7d7d7',
  backgroundActive: '#ddd',
  inputBorder: 'rgb(140, 140, 140)',
  selectionBackground: '#7ec0ee',
  selectionColor: '#111',
  linkColor: '#2562b1',
  summaryColor: '#444',
  inputColor: '#297',
  numberColor: '#407',
  valueColor: '#550',
  bubble1: '#c8c8c8',
  bubble2: '#89dcdc',
  menuBackground: '#bbb',
  menuHighlight: '#aaa',
  errorColor: '#f00',
  actionColor: '#444',
  primaryActionColor: '#5a5',
  actionTextColor: '#ccc',
  disabledActionColor: '#bbb',
  disabledActionTextColor: '#888',
  codeTheme: 'eclipse',
}
