export default {
  dark: {
    foreground: '#eee',
    lightTextColor: '#ccc',
    background: '#222427',
    inputBorder: 'rgb(91, 91, 91)',
    selectionBackground: 'cyan',
    selectionColor: '#eee',
    linkColor: 'cyan',
    inputColor: '#bbb',
    bubble1: '#595959',
    menuBackground: '#898989',
  },
  light: {
    foreground: '#111',
    lightTextColor: '#444',
    background: '#eee',
    inputBorder: 'rgb(140, 140, 140)',
    selectionBackground: 'green',
    selectionColor: 'green',
    linkColor: 'blue',
    inputColor: '#222',
    bubble1: '#c9c9c9',
    menuBackground: '#a7a7a7',
  },
}
